srcs/frontend/src/App.js
1. chakra-ui를 사용하기 위해서 설치하는 것 외에도 App.js에 추가해줘야 하는 부분이 있었습니다.
어쩐지 디자인이 안 먹더라... 그래서 추가했습니다!
=> Feat: add ChakraProvider to use chakra-ui

srcs/frontend/src/frienddata.json, srcs/frontend/src/userdata.json
더미데이터용 브랜치입니다
최대한 원래 db랑 똑같이 만들었습니다람쥐
=> Feat: add user & friend data json file

srcs/frontend/src/App.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/MainPage.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx
App.tsx에서 display가 묶여있던 부분을 해제하였고 이후 choicePage에서 sidebar와 내용을 띄우는데는 성공하였습니다.
차후 사이드바에 내용을 "세로로" 붙여넣을 예정입니다. 아직 세로로 안 된다는 소리입니다 하하하...
=> Feat: 한 페이지에 sidebar 띄우기 성공

srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx
기존 세팅에서 sidebar가 세로로 출력되도록 세팅값을 변경했습니다.
container였던 것을 box로 바꾸고 sidebar에서 linkItem을 순회하면서 이름을 하나씩 출력하도록 세팅했는데 이걸 바탕으로 필요한 기능을 계속 얹어낼 예정입니다
=> Fix: sidebar 기본 세팅

srcs/backend/package-lock.json, srcs/backend/package.json, srcs/backend/src/user/dto/user-login.dto.ts
1. dto 파일에서 데이터의 유효성을 체크하는 데 사용하는 `class-validator`를 설치함.
2. UserLoginDto에 필요한 데코레이터를 추가함.
=> Feat: install class-validator to check data validation and use in dto

srcs/frontend/.gitignore, srcs/frontend/src/components/pages/MainPage.tsx
1. 메인페이지에서 로그인 버튼을 눌렀을 때 42로그인 화면으로 넘어가게 설정함.
2. 환경변수 값을 저장한 .env 파일이 있어야 함.
3. .env 파일에 환경변수를 저장할 때 환경변수 이름에 `REACT_APP`이 접두사로 있어야만 실행됨. 이걸 붙이지 않으면 제대로 읽어오지 못함
=> Feat: link to 42 login uri when click the login button

srcs/frontend/package-lock.json, srcs/frontend/package.json, srcs/frontend/public/data/chatdata.json, srcs/frontend/src/App.tsx, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/RandomButton.tsx, srcs/frontend/src/components/pages/ChattingPage.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx
- 기본 채팅 페이지와 레이아웃 설정 그리고 해당 채팅 방을 만들기 위한 데이터를 추가
- chakra ui에 있는 아이콘 사용(private 구분) -> `npm i @chakra-ui/icons` 다운
```tsx
// App.tsx : route 추가
<Route path="chatting" element={<ChattingPage />} />
// ChoicePage.tsx : button navigate 설정
navigate("/chatting");
```
=> Feat: init chatting - chatting room & random button

srcs/backend/src/auth/auth.controller.ts, srcs/backend/src/user/dto/user-login.dto.ts, srcs/backend/src/user/user.entity.ts, srcs/backend/src/user/user.repository.ts, srcs/frontend/src/App.css, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/MainPage.tsx
=> Comments: add comments to understand well

srcs/backend/node_modules/.package-lock.json, srcs/backend/src/chat/chat.entity.ts
1. 채팅 관련 테이블 정보 저장하는 chat.entity.ts에 주석 추가함.
2. 몇몇 속성에 대해 default 값을 추가함.
=> Fix: add comments to chat entity and some default values

srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GameData.ts, srcs/frontend/src/components/game/GameInterface.ts, srcs/frontend/src/components/game/GameRoom.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/game/PlayerInfo.tsx, srcs/frontend/src/components/game/modules/Interface/chatInterface.ts, srcs/frontend/src/components/game/modules/Interface/gameMatchInterface.ts, srcs/frontend/src/components/game/modules/Interface/userInterface.ts, srcs/frontend/src/components/game/modules/api.ts, srcs/frontend/src/components/game/modules/login/login.ts
component/game 폴더를 추가했습니다.
각 파일마다 작성된 주석을 읽어보시고 부족한 부분이 있으면 알려주세요! (주석은 계속 추가예정)
1. Game : game component의 메인이 되는 부분, 서버와 통신
2. GameData : 게임 데이터라고 되어있지만 게임내에서 네트와 패들, 각종 화면을 그리기 위한 데이터를 가지고 있습니다. 
3. GameInterface : 게임 유저, 게임 방, 게임 상태 등을 가지고 있습니다. 
4. GameRoom : 게임 방에 대한 부분
5. GameScreen : 실질적으로 게임화면을 보여주는 부분
6. PlayerInfo : 게임을 시작할 때 필요한 유저에 대한 정보를 가지고 있습니다. 이 부분은 조금 더 생각을 해봐야 할 것 같아요. 
component/game/module 폴더가 있습니다.
레퍼런스를 참고해서 작성하였고 사용한 데이터와 api가 다르기때문에 계속해서 수정할 예정입니다.
=> Feat: add game component and add test module 

srcs/backend/src/auth/auth.controller.ts, srcs/backend/src/main.ts
1. 백엔드 폴더에서 포트번호가 안 바뀌어 있어서 수정했습니다.
2. `main.ts`에 있는 포트번호를 수정했습니다.
3. 프론트에서 42api 호출하는 url 수정했습니다.
4. 노션 확인하시고 백엔드 폴더의 config/default.yml 파일과 프론트 폴더의 .env 파일 수정해주세요.
=> Fix: modify backend port number

srcs/backend/src/auth/auth.controller.ts
1. cookie에 intra_id 정보도 포함시켰습니다.
=> Fix: add intra_id to cookie

srcs/backend/node_modules/.package-lock.json, srcs/backend/package-lock.json, srcs/backend/package.json, srcs/backend/src/app.controller.ts, srcs/backend/src/auth/auth.controller.ts, srcs/backend/src/friend/friend.controller.ts, srcs/backend/src/main.ts, srcs/backend/src/user/user.controller.ts, srcs/frontend/src/components/sidebar/FriendList.tsx
api를 조금 더 보기 편하게 변경하였습니다.
swagger를 들어가셔서 확인하는 법은 localhost:9633/api로 들어가시면 됩니다.
차후에 swagger 문서에 example이 뜨도록 추가해둘건데 (주석같은 개념) 나중엔 노션 문서보다 더 한 눈에 보기 편하게 만들 예정입니다.
지금은 있는 api만 있어요!
=> Feat: swagger setting

srcs/frontend/src/App.tsx, srcs/frontend/src/components/chatting/ChattingRoom.tsx, srcs/frontend/src/components/pages/ChattingRoomPage.tsx
=> Fix : 페이지, 함수 이름 수정

srcs/backend/package-lock.json, srcs/backend/package.json, srcs/backend/src/app.module.ts, srcs/backend/src/profile/tfaCodeMaker.ts, srcs/backend/src/user/dto/user-default.dto.ts, srcs/backend/src/user/user.controller.ts, srcs/backend/src/user/user.entity.ts, srcs/backend/src/user/user.repository.ts, srcs/backend/src/user/user.service.ts, srcs/frontend/src/components/mypage/MyPageModal.tsx, srcs/frontend/src/components/mypage/tfa.tsx, srcs/frontend/src/components/mypage/tfaCodeCheck.tsx, srcs/frontend/src/components/pages/MyPage.tsx
1. 메일 아이콘을 클릭할 경우 2차인증 메일 주소를 입력할 수 있습니다.
2. 입력된 메일 주소로 whathappenedto2nd@gmail.com 계정이 2차인증 이메일을 발송합니다.
3. user 테이블에 tfaCode(string)와 tfaAuthenticated(boolean)이 추가되었습니다.
4. 메일러 모듈이 추가되었으므로 npm i 해주세용
=> FEAT: send TFA mail

srcs/frontend/src/App.tsx, srcs/frontend/src/components/interface/IUserProps.tsx, srcs/frontend/src/components/mypage/MyProfile.tsx, srcs/frontend/src/components/pages/MyProfilePage.tsx
fix : myprofile 수정(기본 css 및 파일 정리)
=> fix : myprofile 수정(기본 css 및 파일 정리)

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/App.tsx, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/WaitingRoom.tsx, srcs/frontend/src/styles/chat.styles.ts, srcs/frontend/src/styles/waiting.styles.ts
1. 임시로 채팅방을 생성할 수 있는 채팅방 대기 방을 만들고(후에 영웅님 파트로 옮겨가야 함)
2. 채팅방 생성하면 채팅방으로 이동
3. 채팅방에서 메세지를 보내면
내가 보낸 메세지는 노란색으로 닉네임 없이 오른쪽에 뜨고
남에게 받은 메세지는 흰색으로 닉네임과 함께 왼쪽에 뜸
=> Chatting service

srcs/backend/src/games/class/game-ball.class.ts, srcs/backend/src/games/class/game-paddle.class.ts, srcs/backend/src/games/class/game-room.class.ts, srcs/backend/src/user/user.service.ts, srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GameData.ts, srcs/frontend/src/components/game/GamePlayerInfo.tsx, srcs/frontend/src/components/game/GameRoom.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/pages/GamePage.tsx
=> Feat: change GameInterface path

srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/mypage/MyPageModal.tsx, srcs/frontend/src/components/mypage/UserProfile.tsx, srcs/frontend/src/components/mypage/tfa.tsx, srcs/frontend/src/components/mypage/tfaCodeCheck.tsx
=> Fix: component myPage restore

srcs/backend/src/friend/friend.service.ts, srcs/backend/src/user/user.controller.ts, srcs/backend/src/user/user.module.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/sidebar/SideBar.tsx, srcs/frontend/src/components/sidebar/UserList.tsx
친구가 온라인 할 경우 온라인 유저 리스트에서도 동시에 뜨는 미묘한 상황 해결
=> Fix: onlineUser 중복 데이터 삭제

srcs/backend/src/friend/friend.controller.ts, srcs/backend/src/friend/friend.repository.ts, srcs/backend/src/friend/friend.service.ts, srcs/frontend/src/components/mypage/MyPageModal.tsx, srcs/frontend/src/components/mypage/tfa.tsx, srcs/frontend/src/components/sidebar/UserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/ContextMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/AddFriendMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/BlockMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/RemoveFriendMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx, srcs/frontend/src/hooks/useRemoveFriend.tsx
리렌더링 안되던 문제를 useQuery의 캐시를 밀어서 해결하였습니다.
또한 추가적으로 친구 삭제 (block과 다른 개념)를 추가해두었습니다.
=> Fix: sidebar 우클릭 수정 &  리렌더링 문제 해결

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.entity.ts, srcs/backend/src/chat/chat.module.ts, srcs/backend/src/chat/chat.repository.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/chatuser.entity.ts, srcs/backend/src/chat/chatuser.repository.ts, srcs/backend/src/chat/dto/chat.dto.ts, srcs/backend/src/chat/dto/chatuser.dto.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GamePlayerInfo.tsx, srcs/frontend/src/components/game/GameRoom.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/interface/IChatProps.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/HomePage.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx, srcs/frontend/src/components/sidebar/UserItem.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/BlockMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
1. 사이드바 상단 구역을 누르면 /home으로 가도록 설정
2. 방에 들어갔을 시 방에 있는 유저 리스트들이 사이드바에 출력되도록 설정
3. 방에서 사람들이 채팅을 칠 때 치는 사람의 닉네임을 우클릭하면 contextmenu가 뜨도록 수정 하였습니다!
=> Fix: 방에 들어갔을 시 방 인원 출력 및 자잘한 기능 추가

srcs/frontend/src/components/chatting/CreateButton.tsx, srcs/frontend/src/components/pages/ChattingRoomPage.tsx
=> feat: 채팅방 버튼 생성

srcs/frontend/src/components/sidebar/FriendItem.tsx, srcs/frontend/src/components/sidebar/FriendList.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx, srcs/frontend/src/components/sidebar/UserItem.tsx, srcs/frontend/src/components/sidebar/UserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx, srcs/frontend/src/hooks/useAddFriend.tsx
friend / online / chat 세 형식으로 contextmenu를 구분지어서 나오도록 1차적으로 세팅하였습니다.
=> Fix: 방에 들어갔을 시 contextmenu 다르게 세팅, 1차 완료

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.repository.ts, srcs/backend/src/chat/chatuser.repository.ts, srcs/frontend/src/components/chatting/Chatting.tsx
방에서 host가 나갈 때 남은 유저가 있으면 제일 먼저 들어온 유저에게 host가 자동으로 넘어가도록 세팅하였습니다.
=> Fix: 방을 나갈 때 남은 유저가 있으면 host 넘겨주기

srcs/frontend/src/api/api.ts, srcs/frontend/src/components/chatting/CheckPassword.tsx
=> fix: 모달창 Re-rendering 문제 해결

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/CheckPassword.tsx
=> fix : ChatUser 테이블 데이터 저장 문제 해결

srcs/backend/src/user/user.entity.ts, srcs/backend/src/user/user.service.ts, srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/interface/IGameProps.tsx
유저 엔티티에 nullable을 올렸는데 안올라가서 다시 올립니다.
=> 'Fix: userEntity add nullable

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chatuser.repository.ts, srcs/frontend/src/components/chatting/Chatting.tsx
1. 채팅방에서 음소거된 유저는 혼자 떠들게 함.(다른 사람 채팅방에 안 보이고 본인은 간 것처럼 보임)
=> Feat: handle muted user

srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/interface/IGameProps.tsx, srcs/frontend/src/components/interface/IUserChatProps.tsx, srcs/frontend/src/components/interface/IUserProps.tsx, srcs/frontend/src/components/pages/GamePage.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx
프론트에서도 게임 승률 타입 바꿔놓았습니다.
화면 창 줄일때 컴포넌트가 사이드바를 침범하거나 크기가 제대로 안 변하는 문제를 해결했으니 참고하시면 좋을 것 같아요.
=> Feat: frontend sidebar screen fix & game ratio type change

srcs/frontend/src/styles/chat.styles.ts
=> Feat: frontend chat css

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.service.ts, srcs/frontend/src/components/sidebar/contextmenu/UI/HostApproveMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
=> Fix: HOST 넘기는 기능 완성

srcs/backend/src/user/dto/user-default.dto.ts, srcs/backend/src/user/user.controller.ts, srcs/backend/src/user/user.entity.ts, srcs/backend/src/user/user.repository.ts, srcs/backend/src/user/user.service.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/interface/IUserProps.tsx, srcs/frontend/src/components/mypage/Signup.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx
1. 처음 가입했을 때 프로필을 바꾸는 창이 뜹니다
2. 이미 가입했던 사람이라면 바로 choice page로 넘어갑니다
=> FEAT: Change profile when first register

srcs/backend/src/games/enum/games.enum.ts, srcs/backend/src/games/games.controller.ts, srcs/backend/src/games/games.entity.ts, srcs/backend/src/games/games.gateway.ts, srcs/backend/src/games/games.repository.ts, srcs/backend/src/games/games.service.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/game/Game.tsx, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/interface/IGameProps.tsx
1. 게임 유저가 새로고침/뒤로가기/게임 중 방나가기 등 비정상적으로 종료되었을 때 1:-1의 스코어로 저장하도록 했습니다.
2. 게임 저장 시 중복 저장되는 문제를 해결했습니다.
3. 위의 경우 GAME_SAVED_ONE_OUT & GAME_SAVED_TWO_OUT로 게임 상태를 변경하고 프론트에 전달합니다.
4. 프론트에서 비정상적인 종료 시에도 상대방의 승리라고 표시할 수 있도록 했습니다.
=> Feat: game user disconnect handling 

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/chatuser.repository.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/sidebar/FriendItem.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameSpectactorMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
게임중인 친구가 있을 때 그 친구에게 게임 관전할 수 있는 우클릭 메뉴를 추가해주었습니다.
다만 비밀번호가 있을 때 영웅님이 만든 컴포넌트를 사용했는데 뭔가 세팅을 잘못한건지 자동으로 꺼짐....
비번 없을 땐 잘 들어가는 거 확인했습니다!
=> Feat: 게임 관전 func 추가. 기능오류 아직 있음

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/chatuser.repository.ts
1. 나를 차단한 사람의 채팅방에 내가 보낸 메세지가 안 뜨게 처리하는 것.. 아직 테스트는 못 함.
2. 디비의 User 테이블에 socket_id 속성이 추가되어야 함.
=> Feat: handle blocked user

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.module.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/user/dto/user-default.dto.ts, srcs/backend/src/user/user.entity.ts, srcs/backend/src/user/user.repository.ts
1. User 테이블에 socket_id 컬럼 추가함. 하면서 다른 코드도 좀 손봤음... dto 사용하는..
2. 그리고 이전 풀리퀘에서 에러나는 부분 고침
=> Feat: add socket_id column to User entity

srcs/frontend/src/components/mypage/UserProfile.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/HomePage.tsx
1. 프로필/내닉네임 으로 접근할 때 profile로 리디렉션하게 만들었습니다.
2. signup 페이지에서 choice page도 보이는 이슈를 수정했습니다.
=> Fix: show only sign up page

srcs/backend/src/games/games.controller.ts, srcs/backend/src/games/games.gateway.ts, srcs/backend/src/user/user.entity.ts, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/interface/IUserProps.tsx, srcs/frontend/src/components/mypage/History.tsx
getGameHistory api에서 `await axios.get('api/games/${id}')`를 `await axios.get('/games/${id}')`로 수정했습니다.
게임 게이트웨이에서 namespace로 api/games라고 설정해줘서 api에서도 api/games로 불러와야 된다고 생각했네요.
수정하니 프론트에 게임 히스트리 잘 불러와집니다!
=> Feat: frontend success get game history api

srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/SideBar.tsx
방장일 때만 방 세팅을 변경할 수 있도록 작동할 버튼을 만들어두었습니다.
아직 기능구현은 되지 않았습니다...! 온리 버튼!
=> Feat: 방장일 때 방 관련 세팅 변경할 수 있는 버튼 추가-> 기능은 아직 미구현

srcs/backend/src/chat/chat.gateway.ts
join-room할 때 중복데이터가 이미 있는 경우 방어하는 코드 생성
=> Feat: 중복데이터 있을 시 여러 번 안 들어가게 세팅(join-room)

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/EditButton.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameSpectactorMenu.tsx
본인이 host일 때 방 설정을 변경할 수 있는 기능을 추가하였습니다 :)
채팅으로 잘 되는 지 확인하려고 했는데 이건 아직 기능 수정때문에 확인할 수 없어서 추후 수정이 필요한 경우 수정하겠습니다
=> Feat: host일 때 방 설정 변경하는 기능 추가

srcs/backend/src/profile/multerOption.ts, srcs/backend/src/profile/tfaCodeMaker.ts, srcs/backend/src/user/user.controller.ts, srcs/frontend/src/App.tsx, srcs/frontend/src/components/mypage/MyPageModal.tsx, srcs/frontend/src/components/mypage/MyProfile.tsx, srcs/frontend/src/components/mypage/UserProfile.tsx, srcs/frontend/src/components/mypage/styles.css, srcs/frontend/src/components/mypage/tfa.tsx, srcs/frontend/src/components/pages/HomePage.tsx, srcs/frontend/src/components/pages/MyProfilePage.tsx, srcs/frontend/src/components/pages/NotFound.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameSpectactorMenu.tsx
1. 잘못된 링크로 접근할 경우 접근할 수 없는 페이지라고 뜹니다.
2. 일부 코드에 주석이 달렸습니다.
3. 일부 코드의 css가 삭제되었습니다.
=> Feat: 404 Page Not Found

srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/EditButton.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/KickMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
kick 눌렀을 때 대상 유저를 잘 내쫒는 것을 확인하였습니다 :)
이젠 킥 된다 히히히
=> Feat: kick func 완성

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/chatuser.repository.ts
백엔드 코드를 빼놓고 프론트만 추가해서 추가 풀리퀘 올립니다 :(
=> Fix: 빠진 기능 추가

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.repository.ts, srcs/backend/src/chat/chat.service.ts, srcs/frontend/src/components/chatting/ChatListItem.tsx, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/CheckPassword.tsx
방 생성, 진입, 나가기, 채팅 1차적으로 확인했습니다
=> Fix: 방 이름에서 id로 param 변경 1차, 우클릭 제외 생성, 진입, 나가기, 채팅 확인 완료

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.service.ts, srcs/frontend/src/components/chatting/Chatting.tsx
=> Fix: 방 생성 시 방 이름 표시 안 되던 문제 수정 완료

srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/EditButton.tsx
=> Fix: 방 생성, 조인 시 방 이름이 제대로 뜨지 않던 문제 해결

srcs/backend/package-lock.json, srcs/backend/package.json, srcs/backend/src/chat/chat.entity.ts, srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/ChatListItem.tsx, srcs/frontend/src/components/chatting/CheckPassword.tsx
- 채팅방 비밀번호 있는경우 암호화해서 저장
- join시에도 처리 완료
- npm i 한번씩 부탁드립니다
=> feat : 채팅방 bcrypt 처리 완료

srcs/backend/src/chat/chat.gateway.ts
=> fix : edit 시에도 암호화 처리 완료

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/ChatListItem.tsx, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/chatting/CheckPassword.tsx, srcs/frontend/src/components/chatting/EditButton.tsx
방에서 edit 할 때 title을 바꾸라는 말은 없어서 password에 빈 배열을 넣으면 공개방, 아닐 경우 새로운 비밀번호로 받게 변경하였습니다.
=> Fix edit func

srcs/frontend/src/components/sidebar/contextmenu/UI/GameSpectactorMenu.tsx
=> Fix: 비밀방일 경우 관전 불가능

srcs/frontend/src/App.tsx, srcs/frontend/src/components/pages/NotFound.tsx
=> Feat: 조건부 렌더링 설정

srcs/backend/src/games/games.controller.ts, srcs/frontend/src/components/mypage/History.tsx, srcs/frontend/src/components/mypage/styles.css
=> feat : history 구현

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.module.ts
chat gateway에 game import 했습니다
=> Feat: backend chat add game import

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.service.ts, srcs/frontend/src/App.tsx, srcs/frontend/src/api/api.ts, srcs/frontend/src/components/chatting/CreateButton.tsx, srcs/frontend/src/components/pages/HomePage.tsx
=> Add conditional randering

srcs/frontend/src/components/chatting/CreateButton.tsx
fix : unused 메세지 해결
- 한번 더 확인 완료
=> fix : unused 메세지 해결

srcs/backend/src/chat/chat.controller.ts, srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/chatuser.entity.ts, srcs/backend/src/chat/chatuser.repository.ts, srcs/backend/src/chat/dto/chatuser-default.dto.ts, srcs/docker-compose.yaml, srcs/frontend/Dockerfile, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/AddAdminMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/RemoveAdminMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
방에서의 권한을 host / member 에서 host / admin / member로 나누었습니다.
관련해서 코드가 수정이 덜 된 부분이 있을 수 있으니 테스트 필수
=> Fix chat user status

srcs/frontend/src/components/interface/IUserChatProps.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
=> Fix: role 관련 에러 수정

srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
이로써 kick은 admin & member에게만 할 수 있게 되었다.
=> Fix: admin 상태일 때 host에게는 kick 안 뜨게 수정

srcs/frontend/src/components/mypage/UserProfile.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx
feat : 다른 유저 프로필에 히스토리 추가 & unused import 삭제
=> feat : 다른 유저 프로필에 히스토리 추가 & unused import 삭제

srcs/backend/src/chat/chatuser.repository.ts, srcs/frontend/src/components/sidebar/RoomUserItem.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
=> Fix admin func

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/sidebar/FriendList.tsx, srcs/frontend/src/components/sidebar/RoomUserItem.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/UserItem.tsx, srcs/frontend/src/components/sidebar/UserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
어제 yeslee님의 조언을 받아 각 리스트가 무엇을 뜻하는 지 css로 가시적으로 보이게 수정하였습니다.
=> Add css for sidebar list

srcs/backend/src/chat/chat.service.ts, srcs/backend/src/chat/dto/chatuser-default.dto.ts, srcs/frontend/src/components/sidebar/RoomUserItem.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UserContextmenu.tsx
게임중이면 우클릭에서 게임초대가 뜨지 않도록 수정하였습니다.
=> Feat: 게임중인 사람 초대 불가능

srcs/frontend/src/components/chatting/Chatting.tsx
우클릭에 많은 정보들을 넣어줘야하는데 chatting에서 넣어주기 힘들어서 채팅 창 안에서의 우클릭은 뺐습니다.
=> Fix: 채팅창 우클릭 기능 삭제

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx
1. 내가 블락한 사람이 나를 초대할 때 초대가 안 되게 함. -> 에러 팝업만 뜨고 사라짐.
=> Feat: handle blocked user cannot invite blocker

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/chatting/Chatting.tsx, srcs/frontend/src/components/pages/ChattingRoomPage.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/HomePage.tsx, srcs/frontend/src/components/pages/MyProfilePage.tsx
모든 페이지에서 invite(DM)을 받을 수 있게 수정
=> Feat: 모든 페이지에서 DM 받을 수 있게 세팅

srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/games/class/game-room.class.ts, srcs/backend/src/games/games.gateway.ts, srcs/frontend/src/components/mypage/DM.tsx, srcs/frontend/src/components/mypage/UserProfile.tsx, srcs/frontend/src/components/pages/ChattingRoomPage.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/pages/HomePage.tsx, srcs/frontend/src/components/pages/MyProfilePage.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx
useEffect 에러나는거 수정하고 invite-DM 함수를 만들었습니다.
=> Feat: frontend add DM & fix useEffect error

srcs/backend/src/chat/chat.gateway.ts, srcs/frontend/src/components/mypage/DM.tsx
invite-DM 작성
1. 초대하는 사람이 이전에 방에 있는 경우
2. 초대받는 사람이 이전에 방에 있는 경우
3. 초대하는 사람과 받는 사람 모두 방에 있는 경우
4. 이전에 참여한 방에 없는 경우
케이스를 나눠서 처리했습니다.
=> Feat: backend add invite DM

srcs/backend/src/auth/auth.controller.ts, srcs/backend/src/chat/chat.gateway.ts, srcs/backend/src/games/games.controller.ts, srcs/backend/src/games/games.gateway.ts, srcs/backend/src/user/user.service.ts, srcs/frontend/src/components/game/GameScreen.tsx, srcs/frontend/src/components/mypage/DM.tsx, srcs/frontend/src/components/mypage/Signup.tsx, srcs/frontend/src/components/pages/ChattingRoomPage.tsx, srcs/frontend/src/components/pages/ChoicePage.tsx, srcs/frontend/src/components/sidebar/RoomUserList.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameInviteMenu.tsx, srcs/frontend/src/components/sidebar/contextmenu/UI/GameSpectactorMenu.tsx
`console.log`와 `this.logger.log` 삭제했습니다.
=> Feat: remove log

srcs/backend/src/chat/chatuser.repository.ts, srcs/frontend/src/components/chatting/Chatting.tsx
평가 준비하면서 있던 문제 수정했습니다. 내일 테스트 필요합니다.
=> Fix: 초대 된 사람의 방 이름 변경 건 & 새로 Host가 되는 사람의 mute 자동 해제
